name: Standard Python Steps
description: Runs the standard steps for Python
inputs:
  PYTHON_VERSION:
    description: The version of Python to use
    required: true
    default: 3.x
  RUN_UNIT_TESTS:
    description: Set to true to run unit tests
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ inputs.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
    
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install flake8
        pip install pylint
      shell: bash
    
    - name: flake8
      run: |
        if [ -d "./tests" ];
        then
          FILES="*.py test/*.py"
        else
          FILES="*.py"
        fi        

        flake8 --ignore=E501,E231 ${FILES}
      shell: bash
    
    - name: pylint
      run: |
        if [ -d "./tests" ];
        then
          FILES="*.py test/*.py"
        else
          FILES="*.py"
        fi        

        pylint --errors-only --disable=C0301 --disable=C0326 ${FILES}
      shell: bash

    - name: unit test
      if: ${{ inputs.RUN_UNIT_TESTS }}
      run: python -m unittest --verbose --failfast  
      shell: bash
