name: Standard Python Steps
description: Runs the standard steps for Python
inputs:
  PYTHON_VERSION:
    description: The version of Python to use
    required: true
    default: 3.x
  RUN_UNIT_TESTS:
    description: Set to true to run unit tests
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ input.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ input.PYTHON_VERSION }}
    
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install flake8
        pip install pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
      shell: bash
    
    - name: flake8
      run: flake8 --ignore=E501,E231 *.py tests/*.py
      shell: bash
    
    - name: pylint
      run: pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
      shell: bash

    - name: unit test
      if: ${{ input.RUN_UNIT_TESTS }}
      run: python -m unittest --verbose --failfast  
      shell: bash
